### ISSUE TITLE
[BUG] The game crashes when selecting Emissive pixels or Enchanted pixels

### ISSUE THREAD

**Issue by WzczChenX** [Traben-0/Entity_Texture_Features#155]
*please make sure you are using the latest ETF version before submitting an issue, you might also find a dev build
fixing this issue already on my discord https://discord.com/invite/rURmwrzUcz in the #dev-blog channel*

**Describe the issue**

Click Player skin settings > Open Skin feature tools > Emissive pixels and then select pixels to crash
Enchant pixels Same problem

**Screenshots**
null...

**Crash log**
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2023-03-18 00:56:09
Description: Narrating screen

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_4185$class_7841.createNarrationMessage(java.util.function.Supplier)" because "this.field_40755" is null
	at net.minecraft.class_4185.method_25360(class_4185.java:99)
	at net.minecraft.class_339.method_37021(class_339.java:312)
	at net.minecraft.class_4185.method_47399(class_4185.java:104)
	at net.minecraft.class_339.method_37020(class_339.java:302)
	at net.minecraft.class_437.method_37056(class_437.java:652)
	at net.minecraft.class_437.method_37062(class_437.java:632)
	at net.minecraft.class_6385.method_37044(class_6385.java:34)
	at net.minecraft.class_437.method_37065(class_437.java:616)
	at net.minecraft.class_437.method_37071(class_437.java:603)
	at net.minecraft.class_757.method_3192(class_757.java:952)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
	at oolloo.jlw.Wrapper.main(Wrapper.java:53)

**Your setup: (please complete the following information):**

- Minecraft version: 1.19.4
- ModLoader: Fabric
- ETF Version 4.3.4
- Does the issue persist with only ETF installed?
- Yes
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue?

**Comment by Traben-0** [comment]
fixed in v4.3.5
