### ISSUE TITLE
[BUG] "Game crashes when making a statue using TheGrimsey's Statues mod."

### ISSUE THREAD

**Issue by daglurkman** [Traben-0/Entity_Texture_Features#265]
*please make sure you are using the latest ETF version before submitting an issue, you might also find a dev build
fixing this issue already on my discord https://discord.com/invite/rURmwrzUcz in the #dev-blog channel*

Basically, it does what it says on the tin. Whenever I use the Hammer to make a statue, the game crashes. (This was on v6.0.1, btw.)

- What happened?
The game crashed because I made statues. Simple as that.
- What were you doing when it happened?
Making a statue (specifically, out of cobblestone.)
**Screenshots**
Since the game crashes as soon as I perform the mentioned action, I can't show you any screenshots.
**Crash log**
---- Minecraft Crash Report ----
// Don't do that.

Time: 2024-05-01 18:09:49
Description: Rendering Block Entity

java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because the return value of "net.minecraft.class_2586.method_11010()" is null
	at traben.entity_texture_features.ETFApi.getUUIDForBlockEntity(ETFApi.java:167)
	at net.minecraft.class_2586.etf$getUuid(class_2586.java:2054)
	at traben.entity_texture_features.features.ETFManager.getETFTextureVariant(ETFManager.java:253)
	at traben.entity_texture_features.utils.ETFUtils2.getETFVariantNotNullForInjector(ETFUtils2.java:45)
	at net.minecraft.class_1921.localvar$blp000$entity_texture_features$etf$mixinAllEntityLayers(class_1921.java:1994)
	at net.minecraft.class_1921.method_24294(class_1921.java)
	at net.minecraft.class_1921.method_23580(class_1921.java:261)
	at net.thegrimsey.statues.client.renderer.StatueRenderer.render(StatueRenderer.java:128)
	at net.thegrimsey.statues.client.renderer.StatueRenderer.method_3569(StatueRenderer.java:38)
	at net.minecraft.class_824.method_23080(class_824.java:98)
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_23077(class_824.java:98)
	at net.thegrimsey.statues.client.screen.StatueEditorScreen.drawStatue(StatueEditorScreen.java:76)
	at net.thegrimsey.statues.client.screen.StatueEditorScreen.method_2389(StatueEditorScreen.java:50)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at traben.entity_texture_features.ETFApi.getUUIDForBlockEntity(ETFApi.java:167)
	at net.minecraft.class_2586.etf$getUuid(class_2586.java:2054)
	at traben.entity_texture_features.features.ETFManager.getETFTextureVariant(ETFManager.java:253)
	at traben.entity_texture_features.utils.ETFUtils2.getETFVariantNotNullForInjector(ETFUtils2.java:45)
	at net.minecraft.class_1921.localvar$blp000$entity_texture_features$etf$mixinAllEntityLayers(class_1921.java:1994)
	at net.minecraft.class_1921.method_24294(class_1921.java)
	at net.minecraft.class_1921.method_23580(class_1921.java:261)
	at net.thegrimsey.statues.client.renderer.StatueRenderer.render(StatueRenderer.java:128)
	at net.thegrimsey.statues.client.renderer.StatueRenderer.method_3569(StatueRenderer.java:38)
	at net.minecraft.class_824.method_23080(class_824.java:98)
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_23077(class_824.java:98)
	at net.thegrimsey.statues.client.screen.StatueEditorScreen.drawStatue(StatueEditorScreen.java:76)
	at net.thegrimsey.statues.client.screen.StatueEditorScreen.method_2389(StatueEditorScreen.java:50)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at net.minecraft.class_437.method_47413(class_437.java:110)

-- Block Entity Details --
Details:
	Name: statues:statue_blockentity // net.thegrimsey.statues.blocks.entity.StatueBlockEntity
Stacktrace:
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_23077(class_824.java:98)
	at net.thegrimsey.statues.client.screen.StatueEditorScreen.drawStatue(StatueEditorScreen.java:76)
	at net.thegrimsey.statues.client.screen.StatueEditorScreen.method_2389(StatueEditorScreen.java:50)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Screen render details --
Details:
	Screen name: net.thegrimsey.statues.client.screen.StatueEditorScreen
	Mouse location: Scaled: (341, 176). Absolute: (683.000000, 352.000000)
	Screen size: Scaled: (683, 353). Absolute: (1366, 705). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Affected level --
Details:
	All players: 1 total; [class_746['Crispyxboxer125'/105, l='ClientLevel', x=-324.12, y=68.00, z=921.88]]
	Chunk stats: 1024, 453
	Level dimension: minecraft:overworld
	Level spawn location: World: (48,76,0), Section: (at 0,12,0 in 3,4,0; chunk contains blocks 48,-64,0 to 63,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 116435 game time, 130848 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, file/miles's Realiable Stew.zip, file/miles's Enchanted Weapons v2.7.zip, file/miles's Enchanted Tools v3.1.zip, file/miles's Enchanted Books v1.1.zip, file/miles's Enchanted Armors v1.7.zip, file/LowOnFire_1.20.1.zip, file/freshly-modded-1-5-1.zip, file/FreshAnimations_v1.9.zip, continuity:default, continuity:glass_pane_culling_fix, file/Simplified Grass.zip, create:legacy_copper

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.5, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1658156032 bytes (1581 MiB) / 3867148288 bytes (3688 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Athlon Gold 3150U with Radeon Graphics     
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 2.39
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x15d8
	Graphics card #0 versionInfo: DriverVersion=30.0.13044.0
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 25991.81
	Virtual memory used (MB): 20616.96
	Swap memory total (MB): 11776.00
	Swap memory used (MB): 1177.42
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Fabric Mods: 
		alloy_forgery: Alloy Forgery 2.1.2+1.20
		appleskin: AppleSkin 2.5.1+mc1.20
		architectury: Architectury 9.2.14
		axesareweapons: Axes Are Weapons 1.7.3
		balm-fabric: Balm 7.2.2
		bclib: BCLib 3.0.14
			wunderlib: WunderLib 1.1.5
		betterend: Better End 4.0.11
		betternether: Better Nether 9.0.10
		citresewn: CIT Resewn 1.1.5+1.20.1
			citresewn-defaults: CIT Resewn: Defaults 1.1.5+1.20.1
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 3.0.0-beta.4+1.20.1
		copycats: Create: Copycats+ 1.20.1-1.2.6
		craftable_create_casings: Craftable Create Casings 1.1
		create: Create 0.5.1-f-build.1417+mc1.20.1
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.10-2
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.3.2+1.20.1
			porting_lib_base: Porting Lib Base 2.3.2+1.20.1
				porting_lib_config: Porting Lib Config 2.3.2+1.20.1
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.2+1.20.1
				porting_lib_utility: Porting Lib Utility 2.3.2+1.20.1
			porting_lib_brewing: Porting Lib Brewing 2.3.2+1.20.1
				porting_lib_core: Porting Lib Core 2.3.2+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.2+1.20.1
			porting_lib_entity: Porting Lib Entity 2.3.2+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.2+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.2+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.2+1.20.1
				porting_lib_common: Porting Lib Common 2.3.2+1.20.1
			porting_lib_models: Porting Lib Models 2.3.2+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.2+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.2+1.20.1
				porting_lib_model_loader: Porting Lib Model Loader 2.3.2+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.2+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.3.2+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.2+1.20.1
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_gametest: Porting Lib GameTest 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		create_structures: Create: Structures 1.1.0
		createmetalwork: Create: Metalwork 1.0.1
		ctov: ChoiceTheorem's Overhauled Village 3.4.3
		entity_model_features: Entity Model Features 2.0.2
		entity_texture_features: Entity Texture Features 6.0.1
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		explorerscompass: Explorer's Compass 1.20.1-2.2.3-fabric
		fabric-api: Fabric API 0.92.1+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+1802ada577
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabricloader: Fabric Loader 0.15.7
			mixinextras: MixinExtras 0.3.5
		forgeconfigapiport: Forge Config API Port 8.0.0
		framework: Framework 0.6.16
			org_javassist_javassist: javassist 3.29.2-GA
			org_reflections_reflections: reflections 0.10.2
		friendsandfoes: Friends&Foes 2.0.10
		ftbessentials: FTB Essentials 2001.2.2
		ftblibrary: FTB Library 2001.2.1
		ftbultimine: FTB Ultimine 2001.1.4
		gammautils: Gamma Utils 1.7.16
		goblintraders: Goblin Traders 1.9.3
		gravelminer: GravelMiner 16.0.2
		guardvillagers: GuardVillagers 2.0.9-1.20.1
			midnightlib: MidnightLib 1.4.1
		indium: Indium 1.0.30+mc1.20.4
		iris: Iris 1.7.0+mc1.20.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		jade: Jade 11.9.0+fabric
		jadeaddons: Jade Addons 5.2.5
		java: Java HotSpot(TM) 64-Bit Server VM 17
		journeymap: Journeymap 5.9.21
			journeymap-api-fabric: JourneyMap API 1.20-1.9-fabric-SNAPSHOT
		lambdynlights: LambDynamicLights 2.3.2+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
			spruceui: SpruceUI 5.0.0+1.20
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.11.2
		mapfrontiers: MapFrontiers 2.6.0
			commonnetworking: Common Network 1.0.2-1.20.1
		minecraft: Minecraft 1.20.1
		modmenu: Mod Menu 7.2.2
		mr_ctov_createstructures: CTOV - Create: Structures 1.0
		mr_ctov_friendsandfoescompat: CTOV - Friends and Foes Compat 2.0
		mythicmetals: Mythic Metals 0.19.7+1.20.1
			additionalentityattributes: Additional Entity Attributes 1.4.0+1.20.0
			cardinal-components-base: Cardinal Components API (base) 5.2.1
			cardinal-components-entity: Cardinal Components API (entities) 5.2.1
			common-protection-api: Common Protection API 1.0.0
		naturescompass: Nature's Compass 1.20.1-2.2.3-fabric
		nodurability: No Durability 1.0.0
		notenoughcrashes: Not Enough Crashes 4.4.7+1.20.1
		owo: oωo 0.11.2+1.20
			blue_endless_jankson: jankson 1.2.2
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.20.1-build.101
		roughlyenoughitems: Roughly Enough Items 12.1.725
			error_notifier: Error Notifier 1.0.9
		sodium: Sodium 0.5.8+mc1.20.1
		sodium-extra: Sodium Extra 0.5.4+mc1.20.1-build.115
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		statues: Statues 1.3
		subterrestrial: Subterrestrial 2.2.0
		trinkets: Trinkets 3.7.2
	Loaded Shaderpack: (off)
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: AMD Radeon(TM) Graphics GL version 3.2.14761 Core Profile Forward-Compatible No Error Context 21.30.44 30.0.13044.0, ATI Technologies Inc.
	Window size: 1366x705
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, fabric, file/miles's Realiable Stew.zip, file/miles's Enchanted Weapons v2.7.zip, file/miles's Enchanted Tools v3.1.zip, file/miles's Enchanted Books v1.1.zip, file/miles's Enchanted Armors v1.7.zip, file/LowOnFire_1.20.1.zip, file/freshly-modded-1-5-1.zip, file/FreshAnimations_v1.9.zip, continuity:default, continuity:glass_pane_culling_fix, file/Simplified Grass.zip, create:legacy_copper
	Current Language: en_us
	CPU: 4x AMD Athlon Gold 3150U with Radeon Graphics 
	Server Running: true
	Player Count: 1 / 8; [class_3222['Crispyxboxer125'/105, l='ServerLevel[drop a draco on their head]', x=-324.12, y=68.00, z=921.88]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Statues (statues), Entity Texture Features (entity_texture_features)
**Your setup: (please complete the following information):**
- Minecraft version: 1.20.1
- ModLoader: Fabric
- ETF Version: 6.0.1
- Does the issue persist with only ETF installed?
Yeah.
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue?
I doubt it is. TheGrimsey's Statues isn't that well-known of a mod, probably since it's Fabric exclusive as of this moment.

**Comment by Traben-0** [comment]
hmm, i wasnt aware the block entity state could be null :/ ill look into it for next update
