### ISSUE TITLE
Unexpected Crash

### ISSUE THREAD

**Issue by NaiNonTH** [Traben-0/Entity_Texture_Features#86]
**Mod Version:** 4.0.beta.1
**Minecraft Version:** 1.19

**Crash Report:**
_N/A_

**Log:**
[2022-07-20-2.log](https://github.com/Traben-0/Entity_Texture_Features/files/9150206/2022-07-20-2.log)

## Highlighted
```
[20:01:32] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering entity in world
	at net.minecraft.class_898.method_3954(class_898.java:172) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22977(class_761.java:1567) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1315) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1039) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:816) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1143) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:734) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
	at java.util.Optional.of(Optional.java:113) ~[?:?]
	at net.minecraft.class_4668$class_4683.<init>(class_4668.java:243) ~[client-intermediary.jar:?]
	at net.minecraft.class_1921.method_34827(class_1921.java:117) ~[client-intermediary.jar:?]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
	at net.minecraft.class_156$2.apply(class_156.java:875) ~[client-intermediary.jar:?]
	at net.minecraft.class_1921.method_25448(class_1921.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_979.handler$bfc000$etf$applyEmissive(class_979.java:1121) ~[client-intermediary.jar:?]
	at net.minecraft.class_979.method_17161(class_979.java:61) ~[client-intermediary.jar:?]
	at net.minecraft.class_979.method_4199(class_979.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_922.method_4054(class_922.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_1007.method_4215(class_1007.java:63) ~[client-intermediary.jar:?]
	at net.minecraft.class_1007.method_3936(class_1007.java:41) ~[client-intermediary.jar:?]
	at net.minecraft.class_898.method_3954(class_898.java:141) ~[client-intermediary.jar:?]
	... 10 more
[20:01:32] [Thread-5/INFO]: Saving Configuration
```

According to the log, it seems like there was an error while loading entities.

P.S. I experienced this crash while playing Multiplayer.

**Comment by wati2006** [comment]
I also have this issue. When the game needs to render elytra it crashes instantly.
Here is a crash report:

`---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 7/20/22, 5:28 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4)
	at java.util.Objects.requireNonNull(Objects.java:208)
	at java.util.Optional.of(Optional.java:113)
	at net.minecraft.client.render.RenderPhase$Texture.<init>(RenderPhase:243)
	at net.minecraft.client.render.RenderLayer.method_34827(RenderLayer:117)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at net.minecraft.util.Util$2.apply(Util:875)
	at net.minecraft.client.render.RenderLayer.getArmorCutoutNoCull(RenderLayer:130)
	at net.minecraft.client.render.entity.feature.ElytraFeatureRenderer.handler$zzp000$etf$applyEmissive(ElytraFeatureRenderer:621)
	at net.minecraft.client.render.entity.feature.ElytraFeatureRenderer.render(ElytraFeatureRenderer:61)
	at net.minecraft.client.render.entity.feature.ElytraFeatureRenderer.render(ElytraFeatureRenderer:22)
	at net.minecraft.client.render.entity.LivingEntityRenderer.render(LivingEntityRenderer:145)
	at net.minecraft.client.render.entity.PlayerEntityRenderer.render(PlayerEntityRenderer:63)
	at net.minecraft.client.render.entity.PlayerEntityRenderer.render(PlayerEntityRenderer:41)
	at net.minecraft.client.render.entity.EntityRenderDispatcher.render(EntityRenderDispatcher:141)
	at net.minecraft.client.render.WorldRenderer.renderEntity(WorldRenderer:1567)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1315)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1039)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:816)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1143)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:734)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$zlf000$atTheEndOfFirstCatchBeforePrintingCrashReport(MinecraftClient:6428)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:756)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$zlf000$atTheEndOfFirstCatchBeforePrintingCrashReport(MinecraftClient:6428)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:756)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$zlf000$atTheEndOfFirstCatchBeforePrintingCrashReport(MinecraftClient:6428)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:756)
	at net.minecraft.client.main.Main.main(Main:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at java.base/java.util.Optional.of(Optional.java:113)
	at net.minecraft.class_4668$class_4683.<init>(class_4668.java:243)
	at net.minecraft.class_1921.method_34827(class_1921.java:117)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at net.minecraft.class_156$2.apply(class_156.java:875)
	at net.minecraft.class_1921.method_25448(class_1921.java:130)
	at net.minecraft.class_979.handler$zzp000$etf$applyEmissive(class_979.java:621)
	at net.minecraft.class_979.method_17161(class_979.java:61)
	at net.minecraft.class_979.method_4199(class_979.java:22)
	at net.minecraft.class_922.method_4054(class_922.java:145)
	at net.minecraft.class_1007.method_4215(class_1007.java:63)
	at net.minecraft.class_1007.method_3936(class_1007.java:41)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1567)
	at net.minecraft.class_761.method_22710(class_761.java:1315)
	at net.minecraft.class_757.method_3188(class_757.java:1039)

-- Entity being rendered --
Details:
	Entity Type: minecraft:player (net.minecraft.class_746)
	Entity ID: 17053
	Entity Name: Pabloabelo
	Entity's Exact location: -0.50, -60.00, -7.50
	Entity's Block location: World: (-1,-60,-8), Section: (at 15,4,8 in -1,-4,-1; chunk contains blocks -16,-64,-16 to -1,319,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
	Entity NBT: {AbsorptionAmount:0.0f,Air:300s,Attributes:[{Base:0.10000000149011612d,Name:"minecraft:generic.movement_speed"}],Brain:{memories:{}},DataVersion:3105,DeathTime:0s,EnderItems:[],FallDistance:0.0f,FallFlying:0b,Fire:-20s,Health:20.0f,HurtByTimestamp:0,HurtTime:0s,Inventory:[{Count:1b,Slot:102b,id:"minecraft:elytra",tag:{Damage:0}}],Invulnerable:0b,Motion:[0.0d,-0.0784000015258789d,0.0d],OnGround:1b,PortalCooldown:0,Pos:[-0.5d,-60.0d,-7.5d],Rotation:[-12.599796f,7.6500096f],Score:0,SelectedItemSlot:0,SleepTimer:0s,UUID:[I;-324057781,-786018915,-1294230756,1332157811],XpLevel:0,XpP:0.0f,XpSeed:0,XpTotal:0,abilities:{flySpeed:0.05f,flying:0b,instabuild:1b,invulnerable:1b,mayBuild:1b,mayfly:1b,walkSpeed:0.1f},foodExhaustionLevel:0.0f,foodLevel:20,foodSaturationLevel:5.0f,foodTickTimer:0,warden_spawn_tracker:{cooldown_ticks:0,ticks_since_last_warning:0,warning_level:0}}
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1567)
	at net.minecraft.class_761.method_22710(class_761.java:1315)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1143)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$zlf000$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:6428)
	at net.minecraft.class_310.method_1514(class_310.java:756)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$zlf000$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:6428)
	at net.minecraft.class_310.method_1514(class_310.java:756)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$zlf000$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:6428)
	at net.minecraft.class_310.method_1514(class_310.java:756)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.class_1007@213b6f6e
	Location: -0.86,-1.09,-3.87 - World: (-1,-2,-4), Section: (at 15,14,12 in -1,-1,-1; chunk contains blocks -16,-64,-16 to -1,319,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Rotation: -12.599796
	Delta: 0.14004779
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1567)
	at net.minecraft.class_761.method_22710(class_761.java:1315)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1143)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$zlf000$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:6428)
	at net.minecraft.class_310.method_1514(class_310.java:756)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$zlf000$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:6428)
	at net.minecraft.class_310.method_1514(class_310.java:756)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$zlf000$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:6428)
	at net.minecraft.class_310.method_1514(class_310.java:756)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Pabloabelo'/17053, l='ClientLevel', x=-0.50, y=-60.00, z=-7.50]]
	Chunk stats: 1024, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 282 game time, 282 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2288)
	at net.minecraft.class_310.method_1514(class_310.java:753)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$zlf000$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:6428)
	at net.minecraft.class_310.method_1514(class_310.java:756)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$zlf000$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:6428)
	at net.minecraft.class_310.method_1514(class_310.java:756)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$zlf000$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:6428)
	at net.minecraft.class_310.method_1514(class_310.java:756)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 644292960 bytes (614 MiB) / 1950351360 bytes (1860 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 9
	Microarchitecture: unknown
	Frequency (GHz): 2.71
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 620
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x5916
	Graphics card #0 versionInfo: DriverVersion=26.20.100.6859
	Graphics card #1 name: NVIDIA GeForce 940MX
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 2048.00
	Graphics card #1 deviceId: 0x134d
	Graphics card #1 versionInfo: DriverVersion=31.0.15.1640
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 27126.52
	Virtual memory used (MB): 23538.35
	Swap memory total (MB): 14963.88
	Swap memory used (MB): 3243.88
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		entity_texture_features: Entity Texture Features 4.0.beta.1
			cloth-config: Cloth Config v6 7.0.73
				cloth-basic-math: cloth-basic-math 0.6.1
		fabric: Fabric API 0.57.0+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.0+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.1+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.25+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.25+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.3+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.10+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.7+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.17+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.9+1f92344ea9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.5+a6d2f785a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabricloader: Fabric Loader 0.14.8
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.19
		modmenu: Mod Menu 4.0.4
		notenoughcrashes: Not Enough Crashes 4.1.6+1.19
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
	Launched Version: fabric-loader-0.14.8-1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce 940MX/PCIe/SSE2 GL version 3.2.0 NVIDIA 516.40, NVIDIA Corporation
	Window size: 1920x1001
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Polygon modes for <face> are disabled in the current profile.' x 6
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Pabloabelo'/17053, l='ServerLevel[New World]', x=-0.50, y=-60.00, z=-7.50]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable
	Client Crashes Since Restart: 4
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Not Enough Crashes (notenoughcrashes)`

**Comment by Traben-0** [comment]
i've run into this myself today, i'm testing a fix then i'll release it

**Comment by NaiNonTH** [comment]
Cool
