### ISSUE TITLE
[1.19] [V4.0.1] [Fabric] Crash

### ISSUE THREAD

**Issue by BemusedLeader10** [Traben-0/Entity_Texture_Features#90]
The game will not load and gives this log:
`Uncaught exception in thread "main"
java.lang.RuntimeException: Mixin transformation of net.minecraft.client.main.Main failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:454)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [entity_texture_features-common.mixins.json:EntityTypeAccessor from mod entity_texture_features] from phase [DEFAULT] in config [entity_texture_features-common.mixins.json] FAILED during PREPARE
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:585)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:543)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	... 7 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: The specified mixin 'traben.entity_texture_features.mixin.EntityTypeAccessor' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:865)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540)
	... 13 more
Caused by: java.lang.ClassNotFoundException: The specified mixin 'traben.entity_texture_features.mixin.EntityTypeAccessor' was not found
	at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1314)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:858)
	... 16 more
`
I am only running the newest version of fabric api (fabric-api-0.58.0+1.19) and entity texture features (entity_texture_features_fabric-4.0.1)

**Comment by BemusedLeader10** [comment]
Is anyone else able to replicate this?

**Comment by Traben-0** [comment]
I cannot replicate this does it happen every time? can you post the full crash log?

**Comment by BemusedLeader10** [comment]
[latest.log](https://github.com/Traben-0/Entity_Texture_Features/files/9195947/latest.log)

**Comment by Traben-0** [comment]
[entity_texture_features_fabric-4.0.1.zip](https://github.com/Traben-0/Entity_Texture_Features/files/9230933/entity_texture_features_fabric-4.0.1.zip)
can you try this version?

**Comment by BemusedLeader10** [comment]
I can this version as well, but I updated fabric api and played om 1.19.1 (previously 1.19) and the game launched. So fixed for now?

**Comment by Traben-0** [comment]
must be this is an issue with mixins at launch and should happen every time i'm guessing a corrupt download maybe
